mrhooray/crc-rs

src/crc32.rs
src/crc64.rs
tests/hash.rs

Exports implementations of std::hash::Hasher for crc32::Digest and
crc64::Digest. This allows any types which #[derive(Hash)] to easily
hash using one of the CRC implementations.

Implementation of std::hash::Hasher trait

---

Cargo.toml
build.rs
src/crc32.rs
src/crc64.rs
src/lib.rs

this adds support for `no_std` applications/libraries (like microcontrollers) by using conditional features
- rust-lang/cargo#633
On nightly with no_std:
```
Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
Running target/debug/deps/crc-c3e90d0dfab413be
running 0 tests
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured
Running target/debug/deps/crc-9d7b680262789a74
running 10 tests
test crc32::checksum_castagnoli ... ok
test crc32::checksum_ieee ... ok
test crc32::digest_castagnoli ... ok
test crc32::checksum_koopman ... ok
test crc32::digest_ieee ... ok
test crc64::checksum_ecma ... ok
test crc32::digest_koopman ... ok
test crc64::digest_iso ... ok
test crc64::checksum_iso ... ok
test crc64::digest_ecma ... ok
test result: ok. 10 passed; 0 failed; 0 ignored; 0 …
```

add no_std feature

---

Cargo.toml
build.rs
src/crc32.rs
src/crc64.rs
src/lib.rs
src/util/Cargo.toml
src/util/lib.rs

cc @vitiral 
plan to publish new version after land this

use internal crate to share make table functions

---

Cargo.toml
src/crc32.rs
src/crc64.rs
src/lib.rs

See rust-lang/cargo#4866 for explanation.

Avoid a direct dependency on build_const

---

Cargo.toml
benches/bench.rs

This makes them run on stable and also shows throughput of the CRC calculating functions, which is a more useful measure than time.

Port the benchmarks to criterion

---

benches/bench.rs
build.rs
src/crc16.rs
src/crc32.rs
src/crc64.rs
src/lib.rs
src/util.rs
tests/crc.rs
tests/hasher.rs

This pull request updates the code base so that all Clippy lint warnings are resolved, with the exception of the unreadable_literal warning in auto-generated tables. I am unaware of a way to make the code generator format the literals properly. However, as the unreadable_literal lint is just for stylistic purposes, ignoring it has no impact on the functionality or performance of the crate.
All non-benchmark tests have been run and are passing. Additionally, the code has been formatted with  rustfmt.

Address clippy lint warnings.

---

src/lib.rs
src/util.rs

DO NOT MERGE YET - Further testing required and feedback requested.
While exploring #45, I noticed that the logic used to create the u16/u32/u64 CRC tables is nearly identical. I was able to create a macro that generalizes the creation of these tables, and allows for reflection_in and reflection_out to be specified separately (needed for #45) .
I updated the implementations of make_table_crc16(), make_table_crc32(), and make_table_crc64() to simply call the macro, and all existing tests pass. However, I think more CRC variants should be tested before merging (in particular those with no reflection, or mixed input / output reflection).
Would you please take a look at the changes and let me know what you think? If you want to go this route then I will add test cases to hit the different …

Generalize CRC table generator logic into macro

---

.travis.yml
Cargo.toml
README.md
benches/bench.rs
src/crc16.rs
src/crc32.rs
src/crc64.rs
src/lib.rs

- `extern crate ...;` is deprecated.
- Cargo features should be used for "additive" functionality. So, it makes sense to remove the `std` feature.
- Modifying features requires version bump since it could be a breaking change.

Rust edition 2018, `no_std` default, README and CI changes

---

src/crc16.rs
src/crc32.rs
src/crc64.rs

Rust [1.46](https://blog.rust-lang.org/2020/08/27/Rust-1.46.0.html) significantly extends `const fn` support, so now it's possible to perform all calculations at compile time (and hence invoke crc in const context). This PR makes all funcs const (with the only exception `Digest.update`, which mutates state and not yet available in stable).

Use const fn

---

.travis.yml
README.md

Bump MSRV to 1.46

---

Cargo.toml

This crate says it works with crc-catalog 1.0.0, but it can't:
```
Compiling crc v2.0.0-rc.1 (/opt/crc-rs)
error[E0310]: the parameter type `W` may not live long enough
--> src/lib.rs:42:20
|
41 | pub struct Crc<W: Width> {
|                -- help: consider adding an explicit lifetime bound...: `W: 'static +`
42 |     pub algorithm: &'static Algorithm<W>,
|                    ^^^^^^^^^^^^^^^^^^^^^ ...so that the reference type `&'static crc_catalog::Algorithm<W>` does not outlive the data it points at
error: aborting due to previous error
For more information about this error, try `rustc --explain E0310`.
error: could not compile `crc`
To learn more, run the command again with --verbose.
```
This matters when using `-Z minimal-versions` cargo option.

Correct crc-catalog version

---

README.md
benches/bench.rs
src/crc8.rs
src/lib.rs
src/table.rs
src/util.rs
tests/crc.rs

I added support for CRC8 algorithms.
The benchmark results on the README should also be updated, but probably on the original computer that the current ones were run.

Added CRC8 support

---

src/lib.rs

I needed a way to feed a Digest a stream of bytes while checking the CRC
for possible matches after each byte. Using CRC::crc directly would make
this O(n^2), so I looked to Digest. Because Digest::finalize consumes
self, it must be thrown out after each finalize operation. This is
probably what you want in the general case, but not in my slightly weird
case.
This problem can be solved by allowing Digest to be duplicated, thereby
letting the user "fork" the CRC state as desired. (This also enables
certain niche CRC-search algorithms.)
I went with Clone rather than Copy because making Digest Copy seemed
potentially error-prone; Clone has the advantage of requiring explicit
intent.
Here's an example (not included in the commit message for brevity) of a method enabled by this change.
```rust …
```

impl Clone for Digest

---

src/lib.rs

This allows for new implementations to be added without breaking API compatibility.

Make Crc generic over implementation

---

benches/bench.rs
src/crc32.rs
src/crc32_fast.rs
src/lib.rs
src/table.rs

This introduces an implementation of the slice-by-16 algorithm that calculates the crc of 16 bytes in one step instead of iterating the input bytewise. As a tradeoff the necessary lookup-table is 16x bigger, so in case of a 32bit crc it's 16kB.
Should I add implementations for the other widths in this PR or do you prefer separate PRs? I'd imagine review is simpler in separate PRs but merging the benchmarks might get annoying. I don't really care, I can do both.
Benchmark on a Ryzen 7 3800X:
```
$ cargo bench 32
Running benches/bench.rs (target/release/deps/bench-9c684e23a65bab14)
checksum/crc32          time:   [30.355 µs 30.357 µs 30.360 µs]
thrpt:  [514.66 MiB/s 514.70 MiB/s 514.75 MiB/s]
checksum/crc32_slice16  time:   [4.5740 µs 4.5812 µs 4.5893 µs]
thrpt:  [3.3249 GiB/s 3.3308 GiB/s …
```

Add slice16

---

benches/bench.rs
src/crc64.rs
src/crc64/bytewise.rs
src/crc64/default.rs
src/crc64/nolookup.rs
src/crc64/slice16.rs
src/lib.rs
src/table.rs

Got around to implement slice16 and no-table flavours for Crc<u64> 
Benches:
```
crc64/default           time:   [29.969 µs 30.022 µs 30.082 µs]
thrpt:  [519.41 MiB/s 520.45 MiB/s 521.37 MiB/s]
crc64/nolookup          time:   [111.28 µs 111.51 µs 111.72 µs]
thrpt:  [139.86 MiB/s 140.12 MiB/s 140.41 MiB/s]
crc64/bytewise          time:   [29.864 µs 29.934 µs 30.004 µs]
thrpt:  [520.77 MiB/s 521.98 MiB/s 523.21 MiB/s]
crc64/slice16           time:   [5.1544 µs 5.1681 µs 5.1839 µs]
thrpt:  [2.9435 GiB/s 2.9525 GiB/s 2.9603 GiB/s]
```

implement slice16 and no-table implementations for width 64

---

.github/workflows/rust.yaml

Updates the `actions/checkout` action used in the GitHub Actions workflows to its newest major version.
Changes in [actions/checkout](https://github.com/actions/checkout):
> ## v3.3.0
> - Implement branch list using callbacks from exec function
> - Add in explicit reference to private checkout options
> - Fix comment typos
>
> ## v3.2.0
> - Add GitHub Action to perform release
> - Fix status badge
> - Replace datadog/squid with ubuntu/squid Docker image
> - Wrap pipeline commands for submoduleForeach in quotes
> - Update @actions/io to 1.1.2
> - Upgrading version to 3.2.0
>
> ## v3.1.0
> - Use @actions/core `saveState` and `getState`
> - Add `github-server-url` input
>
> ## v3.0.2
> - Add input `set-safe-directory`
>
> ## v3.0.1
> - Fixed an issue where checkout failed to run in container …

Update actions/checkout in GitHub Actions workflow to v3

---

.github/workflows/rust.yaml

Basically all of the `actions-rs/*` actions are unmaintained. See <https://github.com/actions-rs/toolchain/issues/216> for more information. Due to their age they generate several warnings in CI runs, for example in https://github.com/mrhooray/crc-rs/actions/runs/4093752674:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions-rs/toolchain@v1, __actions-rs/cargo@v1__. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
To get rid of some of those warnings the occurrences of `actions-rs/cargo` are replaced by direct invocations of `cargo`.

Replace unmaintained actions-rs/cargo action in CI workflow

---

.github/workflows/rust.yaml

Basically all of the `actions-rs/*` actions are unmaintained. See <https://github.com/actions-rs/toolchain/issues/216> for more information. Due to their age they generate several warnings in CI runs, for example in https://github.com/mrhooray/crc-rs/actions/runs/4093752674:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, __actions-rs/toolchain@v1__, actions-rs/cargo@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
To get rid of some of those warnings the occurrences of `actions-rs/toolchain` are replaced by [`dtolnay/rust-toolchain`](https://github.com/dtolnay/rust-toolchain).

Replace unmaintained actions-rs/toolchain actions in CI workflows

---

benches/bench.rs
src/crc128.rs
src/crc128/bytewise.rs
src/crc128/default.rs
src/crc128/nolookup.rs
src/crc128/slice16.rs
src/table.rs

This one is interesting, the speedup is way smaller because of the 128bit (=16 Bytes) wide crc. The speedup is still there but it's debate-able if slice-by-16 or bytewise algorithm should be the default. The lookup table for the slice-by-16 alg is 64 kB large for u128 entries.  
Benches: 
```
crc82/default           time:   [35.621 µs 35.642 µs 35.667 µs]
thrpt:  [438.08 MiB/s 438.38 MiB/s 438.64 MiB/s]
crc82/nolookup          time:   [171.31 µs 171.51 µs 171.75 µs]
thrpt:  [90.974 MiB/s 91.102 MiB/s 91.206 MiB/s]
crc82/bytewise          time:   [35.318 µs 35.323 µs 35.329 µs]
thrpt:  [442.28 MiB/s 442.34 MiB/s 442.41 MiB/s]
crc82/slice16           time:   [25.078 µs 25.084 µs 25.090 µs]
thrpt:  [622.75 MiB/s 622.90 MiB/s 623.05 MiB/s]
```

Add crc128 slice-by-16 and no-table implementations

---

benches/bench.rs
src/crc16.rs
src/crc16/bytewise.rs
src/crc16/default.rs
src/crc16/nolookup.rs
src/crc16/slice16.rs
src/table.rs

Same old stuff for u16. Second to last 🙏 
Benches (this time on a Mac):
```
crc16/default           time:   [41.595 µs 41.660 µs 41.730 µs]
thrpt:  [374.43 MiB/s 375.06 MiB/s 375.65 MiB/s]
crc16/nolookup          time:   [189.08 µs 189.20 µs 189.31 µs]
thrpt:  [82.534 MiB/s 82.586 MiB/s 82.636 MiB/s]
crc16/bytewise          time:   [41.532 µs 41.567 µs 41.609 µs]
thrpt:  [375.52 MiB/s 375.90 MiB/s 376.22 MiB/s]
crc16/slice16           time:   [4.7172 µs 4.7269 µs 4.7378 µs]
thrpt:  [3.2206 GiB/s 3.2281 GiB/s 3.2347 GiB/s]
```

Add crc16 slice-by-16 and no-table implementations

---

README.md
src/crc16/default.rs
src/crc32/default.rs
src/crc64/default.rs
src/crc8/default.rs
src/lib.rs

As the title says, this enables the slice16 optimization as default for all widths but u128
I also tried to document the tradeoffs in the Readme which goes a bit towards #82 but I agree having information about this somewhere in the generated docs would be useful.
Edit: and it re-enables the `#[no-std]` which I accidentally disabled in one of the previous PRs, sorry about that!

use slice16 as default impl on all width but u128 and document the tradeoffs in the Readme

---

Cargo.toml
src/crc128.rs
src/crc128/default.rs
src/crc16.rs
src/crc16/default.rs
src/crc32.rs
src/crc32/default.rs
src/crc64.rs
src/crc64/default.rs
src/crc8.rs
src/crc8/default.rs
src/lib.rs
tests/test_under_all_feature_combinations.sh

As a draft towards #93, and #92
This introduces three crate features which enable choosing the default implementations. The implementation is chosen based on the flag with the most hardware compatibility ( => the highest restrictions on memory usage)
1. NoTable takes precedence over both others
2. Bytewise takes precedence over Slice16 and is the default if no feature is selected
3. Slice16 is used only if no other features are selected

switch impls based on crate features for u8 as an example

---

Cargo.toml
README.md

Just noticed I forgot to update the readme according to the new selection of implementations via the crate features. Sorry about that!

fix readme regarding default impl selection

---

README.md

The readme had a copy-paste error, where it said "slice16-mem-limit" instead of "no-table-mem-limit" sorry for that

Fix error in Readme about feature precedence

---

src/crc128/bytewise.rs
src/crc128/slice16.rs
src/crc16/bytewise.rs
src/crc16/slice16.rs
src/crc32/bytewise.rs
src/crc32/slice16.rs
src/crc64/bytewise.rs
src/crc64/slice16.rs
src/crc8/bytewise.rs
src/crc8/slice16.rs

expose lookup tables

---

Cargo.toml
src/lib.rs
src/table.rs
src/util.rs

Motivation: on AVR compiling the library gives the following error:
> error: values of the type `[[u128; 256]; 16]` are too big for the target architecture

Add cargo features for each CRC width
